name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source src/code/SharedSelenium.Helpers.csproj
    - name: Publish
      run: dotnet nuget push Selenium.Helpers/SharedSelenium.Helpers/src/code/bin/Release/SharedSelenium.Helpers.0.0.1.nupkg --api-key  ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      
      
      
      









